twig:
    default_path: '%kernel.project_dir%/templates'
    paths:
        '%kernel.project_dir%/src/CineBundle/templates/Card': Card
        '%kernel.project_dir%/src/CineBundle/templates/Cine': Cine


when@test:
    twig:
        strict_variables: true
